### ISSUE TITLE
source build-env fails with error code 1

### ISSUE THREAD

**Issue by Drynok** [docksal/ci-agent#35]
Affected ci-agent v1.6

```
#!/bin/bash -eo pipefail
source build-env
Exited with code 1

/usr/local/bin/build-env: pop_scope: head of shell_variables not a temporary environment scope
```

**Comment by lmakarov** [comment]
@Drynok thanks for reporting this!

Not sure why this was affecting some builds, but not others, but this has been fixed now and released in the [1.6.1](https://github.com/docksal/ci-agent/releases/tag/v1.6.1) hotfix release.

You can use the same `1.6` version of the image (e.g. `docksal/ci-agent:1.6-php`) as we do not tag hotfix releases separately.
